# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 549)
        MainWindow.setStyleSheet("/* Style for first menu widget  */\n"
"#main_menu_widget {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 231, 215, 255), stop:1 rgba(122, 215, 255, 255));\n"
"    border-top: 1px solid #434343;\n"
"}\n"
"\n"
"#main_menu_widget QPushButton {\n"
"    border: none;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"}\n"
"\n"
"#main_menu_widget QPushButton:hover {\n"
"    color: #0946F7\n"
"}\n"
"\n"
"#main_menu_widget QPushButton:checked {\n"
"    padding-top: 5px;\n"
"    border-bottom: 5px solid rgb(67, 67, 67)\n"
"}\n"
"\n"
"/* Style for second menu widget  */\n"
"#second_menu_widget  {\n"
"    background-color: rgb(67, 67, 67);\n"
"}\n"
"\n"
"#second_menu_widget QPushButton  {\n"
"    border: none;\n"
"   color: #fff;\n"
"}\n"
"\n"
"#second_menu_widget QPushButton:hover  {\n"
"    color: #EDBB99;\n"
"}\n"
"\n"
"#second_menu_widget QPushButton:checked  {\n"
"    color: rgb(255, 186, 74);\n"
"}\n"
"\n"
"/* Style for search widget  */\n"
"#search_widget QLineEdit {\n"
"    border-radius: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"#search_widget QPushButton {\n"
"    border-radius: 2px;\n"
"    background-color: #fff;\n"
"    border: 1px solid #f0f0f0;\n"
"}\n"
"\n"
"#search_widget QPushButton:pressed {\n"
"    padding-left:5px;\n"
"}\n"
"\n"
"/* Style for main widget  \n"
"#main_widget {\n"
"    border-left: 5px solid #434343;\n"
"    border-right: 5px solid #434343;\n"
"    border-bottom: 5px solid #434343;\n"
"    border-top: 5px solid #434343;\n"
"}\n"
"\n"
"*/")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_menu_widget.setMinimumSize(QtCore.QSize(0, 30))
        self.main_menu_widget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.main_menu_widget.setAutoFillBackground(False)
        self.main_menu_widget.setStyleSheet("background-color:#93BFCF;border-radius:2px;")
        self.main_menu_widget.setObjectName("main_menu_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_menu_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Uploadbtn = QtWidgets.QPushButton(self.main_menu_widget)
        self.Uploadbtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Uploadbtn.setFont(font)
        self.Uploadbtn.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icon/home-4-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Uploadbtn.setIcon(icon)
        self.Uploadbtn.setIconSize(QtCore.QSize(12, 12))
        self.Uploadbtn.setCheckable(True)
        self.Uploadbtn.setChecked(True)
        self.Uploadbtn.setAutoExclusive(True)
        self.Uploadbtn.setObjectName("Uploadbtn")
        self.horizontalLayout.addWidget(self.Uploadbtn)
        self.Livebtn = QtWidgets.QPushButton(self.main_menu_widget)
        self.Livebtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Livebtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icon/user-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Livebtn.setIcon(icon1)
        self.Livebtn.setIconSize(QtCore.QSize(12, 12))
        self.Livebtn.setCheckable(True)
        self.Livebtn.setAutoExclusive(True)
        self.Livebtn.setObjectName("Livebtn")
        self.horizontalLayout.addWidget(self.Livebtn)
        self.databtn = QtWidgets.QPushButton(self.main_menu_widget)
        self.databtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.databtn.setFont(font)
        self.databtn.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./icon/redeem-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.databtn.setIcon(icon2)
        self.databtn.setIconSize(QtCore.QSize(12, 12))
        self.databtn.setCheckable(True)
        self.databtn.setChecked(False)
        self.databtn.setAutoExclusive(True)
        self.databtn.setAutoDefault(False)
        self.databtn.setDefault(False)
        self.databtn.setFlat(False)
        self.databtn.setObjectName("databtn")
        self.horizontalLayout.addWidget(self.databtn)
        self.Aboutusbtn = QtWidgets.QPushButton(self.main_menu_widget)
        self.Aboutusbtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Aboutusbtn.setFont(font)
        self.Aboutusbtn.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./icon/group-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Aboutusbtn.setIcon(icon3)
        self.Aboutusbtn.setIconSize(QtCore.QSize(12, 12))
        self.Aboutusbtn.setCheckable(True)
        self.Aboutusbtn.setAutoExclusive(True)
        self.Aboutusbtn.setObjectName("Aboutusbtn")
        self.horizontalLayout.addWidget(self.Aboutusbtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.main_menu_widget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_widget)
        self.stackedWidget.setAcceptDrops(False)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageupload = QtWidgets.QWidget()
        self.pageupload.setObjectName("pageupload")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.pageupload)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.widget = QtWidgets.QWidget(self.pageupload)
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(0, 60, 645, 64))
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_6.setSpacing(15)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.filepath = QtWidgets.QLineEdit(self.frame)
        self.filepath.setObjectName("filepath")
        self.horizontalLayout_6.addWidget(self.filepath)
        self.selectfilebtn = QtWidgets.QPushButton(self.frame)
        self.selectfilebtn.setMinimumSize(QtCore.QSize(120, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../#022_Data_Entry_Form_for_Excel/ui/icon/folder-3-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectfilebtn.setIcon(icon4)
        self.selectfilebtn.setObjectName("selectfilebtn")
        self.horizontalLayout_6.addWidget(self.selectfilebtn)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setGeometry(QtCore.QRect(0, 140, 641, 64))
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_8.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_8.addWidget(self.label_20)
        self.folderpath = QtWidgets.QLineEdit(self.frame_3)
        self.folderpath.setObjectName("folderpath")
        self.horizontalLayout_8.addWidget(self.folderpath)
        self.selectfolderbtn = QtWidgets.QPushButton(self.frame_3)
        self.selectfolderbtn.setMinimumSize(QtCore.QSize(120, 0))
        self.selectfolderbtn.setIcon(icon4)
        self.selectfolderbtn.setObjectName("selectfolderbtn")
        self.horizontalLayout_8.addWidget(self.selectfolderbtn)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(240, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.launchprocessbtn = QtWidgets.QPushButton(self.widget)
        self.launchprocessbtn.setGeometry(QtCore.QRect(120, 230, 141, 23))
        self.launchprocessbtn.setObjectName("launchprocessbtn")
        self.shell = QtWidgets.QPlainTextEdit(self.widget)
        self.shell.setGeometry(QtCore.QRect(10, 300, 641, 141))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(11)
        self.shell.setFont(font)
        self.shell.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.shell.setAutoFillBackground(False)
        self.shell.setStyleSheet("background-color:rgb(0, 85, 127);color:rgb(255, 255, 127);\n"
"border-radius : 6px;")
        self.shell.setPlainText("")
        self.shell.setObjectName("shell")
        self.checkoutputbtn = QtWidgets.QPushButton(self.widget)
        self.checkoutputbtn.setEnabled(False)
        self.checkoutputbtn.setGeometry(QtCore.QRect(360, 230, 141, 23))
        self.checkoutputbtn.setObjectName("checkoutputbtn")
        self.cancelbtn = QtWidgets.QPushButton(self.widget)
        self.cancelbtn.setEnabled(True)
        self.cancelbtn.setGeometry(QtCore.QRect(250, 270, 141, 23))
        self.cancelbtn.setStyleSheet("")
        self.cancelbtn.setObjectName("cancelbtn")
        self.gridLayout_11.addWidget(self.widget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageupload)
        self.framebyframe = QtWidgets.QWidget()
        self.framebyframe.setObjectName("framebyframe")
        self.label_6 = QtWidgets.QLabel(self.framebyframe)
        self.label_6.setGeometry(QtCore.QRect(520, 60, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("text-align: center;")
        self.label_6.setObjectName("label_6")
        self.playvideobtn_2 = QtWidgets.QPushButton(self.framebyframe)
        self.playvideobtn_2.setGeometry(QtCore.QRect(550, 350, 75, 23))
        self.playvideobtn_2.setObjectName("playvideobtn_2")
        self.framing = QtWidgets.QLabel(self.framebyframe)
        self.framing.setGeometry(QtCore.QRect(20, 50, 471, 351))
        self.framing.setStyleSheet("background-color:#4d5056;")
        self.framing.setText("")
        self.framing.setScaledContents(True)
        self.framing.setObjectName("framing")
        self.stackedWidget.addWidget(self.framebyframe)
        self.pagelive = QtWidgets.QWidget()
        self.pagelive.setStyleSheet("")
        self.pagelive.setObjectName("pagelive")
        self.living = QtWidgets.QLabel(self.pagelive)
        self.living.setGeometry(QtCore.QRect(-10, -10, 691, 491))
        self.living.setStyleSheet("background-color:#4d5056;")
        self.living.setText("")
        self.living.setScaledContents(True)
        self.living.setObjectName("living")
        self.start_frame = QtWidgets.QFrame(self.pagelive)
        self.start_frame.setGeometry(QtCore.QRect(160, 120, 381, 211))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        self.start_frame.setFont(font)
        self.start_frame.setStyleSheet("background:rgb(220, 220, 220);\n"
"border-radius: 10px;")
        self.start_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.start_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_frame.setObjectName("start_frame")
        self.label_2 = QtWidgets.QLabel(self.start_frame)
        self.label_2.setGeometry(QtCore.QRect(170, 10, 41, 41))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./icon/alert.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.start_frame)
        self.label_5.setGeometry(QtCore.QRect(60, 70, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.launchbtn = QtWidgets.QPushButton(self.start_frame)
        self.launchbtn.setGeometry(QtCore.QRect(150, 150, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        self.launchbtn.setFont(font)
        self.launchbtn.setStyleSheet("box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);\n"
"color : rgb(255, 255, 0);\n"
"background : black;\n"
"border-radius: 5px;")
        self.launchbtn.setObjectName("launchbtn")
        self.endbtn = QtWidgets.QPushButton(self.pagelive)
        self.endbtn.setGeometry(QtCore.QRect(310, 410, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        self.endbtn.setFont(font)
        self.endbtn.setStyleSheet("box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);\n"
"color : white;\n"
"background : black;\n"
"border-radius: 5px;")
        self.endbtn.setObjectName("endbtn")
        self.stackedWidget.addWidget(self.pagelive)
        self.pagedata = QtWidgets.QWidget()
        self.pagedata.setObjectName("pagedata")
        self.label_3 = QtWidgets.QLabel(self.pagedata)
        self.label_3.setGeometry(QtCore.QRect(280, 10, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.pagedata)
        self.tableWidget.setGeometry(QtCore.QRect(20, 120, 271, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.frame_2 = QtWidgets.QFrame(self.pagedata)
        self.frame_2.setGeometry(QtCore.QRect(20, 50, 645, 64))
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_7.addWidget(self.lineEdit_11)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.pagedata)
        self.tableWidget_2.setGeometry(QtCore.QRect(380, 120, 271, 271))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.stackedWidget.addWidget(self.pagedata)
        self.pageAboutus = QtWidgets.QWidget()
        self.pageAboutus.setObjectName("pageAboutus")
        self.label_4 = QtWidgets.QLabel(self.pageAboutus)
        self.label_4.setGeometry(QtCore.QRect(390, 180, 47, 13))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.pageAboutus)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.main_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.selectfolderbtn.clicked.connect(self.frame.hide) # type: ignore
        self.selectfilebtn.clicked.connect(self.frame_3.hide) # type: ignore
        self.cancelbtn.clicked.connect(self.frame_3.show) # type: ignore
        self.cancelbtn.clicked.connect(self.frame.show) # type: ignore
        self.selectfilebtn.clicked.connect(self.cancelbtn.show) # type: ignore
        self.selectfolderbtn.clicked.connect(self.cancelbtn.show) # type: ignore
        self.endbtn.clicked.connect(self.start_frame.show) # type: ignore
        self.launchbtn.clicked.connect(self.start_frame.hide) # type: ignore
        self.launchbtn.clicked.connect(self.endbtn.show) # type: ignore
        self.endbtn.clicked.connect(self.endbtn.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Uploadbtn.setText(_translate("MainWindow", "UPLOAD"))
        self.Livebtn.setText(_translate("MainWindow", "LIVE"))
        self.databtn.setText(_translate("MainWindow", "Data"))
        self.Aboutusbtn.setText(_translate("MainWindow", "About US"))
        self.label_18.setText(_translate("MainWindow", "Select Video :"))
        self.selectfilebtn.setText(_translate("MainWindow", "  Select File"))
        self.label_20.setText(_translate("MainWindow", "Select folder : "))
        self.selectfolderbtn.setText(_translate("MainWindow", "  Select Folder"))
        self.label.setText(_translate("MainWindow", "Video Processing"))
        self.launchprocessbtn.setText(_translate("MainWindow", "Launch Process"))
        self.checkoutputbtn.setText(_translate("MainWindow", "Check Output"))
        self.cancelbtn.setText(_translate("MainWindow", "cancel"))
        self.label_6.setText(_translate("MainWindow", "Output Video Player"))
        self.playvideobtn_2.setText(_translate("MainWindow", "Play Video"))
        self.label_5.setText(_translate("MainWindow", "Click if You Are Ready to launch the Live Detection"))
        self.launchbtn.setText(_translate("MainWindow", "Launch"))
        self.endbtn.setText(_translate("MainWindow", "End Live"))
        self.label_3.setText(_translate("MainWindow", "Visualize Data"))
        self.label_19.setText(_translate("MainWindow", "Selectionner les Données: "))
        self.pushButton_4.setText(_translate("MainWindow", "  Select File"))
        self.label_4.setText(_translate("MainWindow", "About Us"))
import resource_rc
